spring:
  datasource:
    url: jdbc:postgresql://5.42.74.164:5432/ARM
    username: ADM_ARM
    password: 1eAI1unjbfKvSgxjKVV9inP92utSAW9PsRWYIVwnQtdRPLu69CZXTwLUdoOh6fIVRqobe9t2mOfBHHpc
  jpa:
    hibernate:
      ddl-auto: update # Hibernate ddl auto (create, create-drop, validate, update),production set to none or comment it
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true

management:
  endpoints.web.exposure.include: 'prometheus, health'
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
  prometheus:
    metrics:
      export:
        enabled: true
  endpoints:
    web:
      base-path: /cxaawsd

resilience4j.rateLimiter:
  configs:
    default:
      timeoutDuration: 6s
      limitForPeriod: 60
      limit-refresh-period: 1s
      registerHealthIndicator: true
      eventConsumerBufferSize: 500000


server:
  port: 80
